# NumPy 

 - NumPy (or Numpy) is a Linear Algebra Library for Python.
 - Numpy is also incredibly fast, as it has bindings to C libraries.
 - Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but  a matrix can still have only one row or one column).



In [1]:
# Importing the library
import numpy as np

### Creating a numpy array
#### from a python list

In [3]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


In [5]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

built-in ways to generate Arrays

#### arange
Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros and ones

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

#### linspace

In [18]:
# Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
# create an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
To create random numbers
#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1]

In [25]:
np.random.rand(2)

array([0.84457062, 0.06555531])

In [26]:
np.random.rand(5,5)

array([[0.87220407, 0.48033302, 0.66365689, 0.76836266, 0.51504884],
       [0.88217666, 0.87681324, 0.87543133, 0.35568125, 0.87999099],
       [0.24170193, 0.70119145, 0.93618532, 0.7764868 , 0.13007992],
       [0.59860016, 0.76636306, 0.8012505 , 0.15969865, 0.8467056 ],
       [0.59947966, 0.80274691, 0.40548571, 0.1794417 , 0.75204678]])

#### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [29]:
np.random.randn(2)

array([-0.64339119,  1.66513307])

In [31]:
df = np.random.randn(5,5)
df

array([[ 1.09470464,  2.0315282 , -1.37633237, -0.64613199, -0.38699105],
       [ 0.50657168,  0.36906414,  0.55397347, -1.77006693, -0.50192577],
       [ 0.87620161,  2.06494211, -0.85738559,  0.15014174, -0.17522845],
       [-1.71847463, -0.6010572 , -0.34141274,  0.44436479, -0.82315453],
       [ 0.21163539,  0.48377451,  0.64800237,  1.00114243, -0.34120999]])

#### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [38]:
np.random.randint(1,100)

45

In [39]:
np.random.randint(1,100,10)

array([18, 85, 73, 53, 26, 28, 69, 63, 95, 90])

####  Array Attributes and Methods

Useful attributes and methods or an array:

In [40]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [42]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [43]:
print(ranarr)

[ 5  9  7 13 28  0 24 28 36 37]


### Reshape
returns a new shape of data

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Useful methods for finding max or min values or to find their index locations using argmin or argmax

In [46]:
ranarr

array([ 5,  9,  7, 13, 28,  0, 24, 28, 36, 37])

In [47]:
ranarr.max()

37

In [48]:
ranarr.argmax()  # gives the index of max value in array

9

In [49]:
ranarr.min()

0

In [50]:
ranarr.argmin()

5

### Shape

Shape is an attribute that arrays have (it is not a method):

In [51]:
## vector
arr.shape  # arr is one-dimensional array

(25,)

In [55]:
# Notice the two sets of brackets - so it becomes two dimanesional array
arr_2d = arr.reshape(1,25)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [56]:
arr_2d.shape

(1, 25)

In [57]:
arr_2d_tran = arr.reshape(25,1)
arr_2d_tran

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [58]:
arr_2d_tran.shape

(25, 1)

### dtype

grabs the data type of the object in the array:

In [59]:
arr.dtype

dtype('int32')